[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --baud 2000000 --monitor-baud 115200 --log-format serial"

[env]
ESP_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
